version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: ventasdb
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend-net

  ventas-api:
    image: vi8letpaz/back-ventas:latest
    container_name: ventas-api
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ventasdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - mysql
    networks:
      - backend-net

  despacho-api:
    image: vi8letpaz/back-despachos:latest
    container_name: despacho-api
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ventasdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - mysql
    networks:
      - backend-net

volumes:
  mysql_data:

networks:
  backend-net:
    driver: bridge
